on:
  push:
      branches:
        - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploying master to website
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASS }}
        server-dir: /home/vectloko/consent-app.vectorhealthcompliance.com/