on:
  push:
      branches:
        - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploying master to website
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.4
    - name: 📂 Sync files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
          host: ${{ secrets.SFTP_SERVER }}
          port: 21098
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          remotePath: /home/vectloko/consent-app.vectorhealthcompliance.com/